#!/usr/bin/env python3
"""Generate docs/api/<subpackage>.md from module docstrings and public signatures.

    python scripts/gen_api_docs.py
"""

from __future__ import annotations

import importlib
import inspect
import pkgutil
from pathlib import Path

import nssc

OUT = Path("docs/api")
SKIP = {"nssc.cli"}


def _doc(obj) -> str:
    d = inspect.getdoc(obj) or ""
    return d.strip()


def _sig(obj) -> str:
    try:
        return str(inspect.signature(obj))
    except (TypeError, ValueError):
        return "(...)"


def document_module(modname: str) -> str:
    mod = importlib.import_module(modname)
    lines = [f"### `{modname}`", ""]
    if _doc(mod):
        lines += [_doc(mod), ""]
    for name, obj in sorted(vars(mod).items()):
        if name.startswith("_") or getattr(obj, "__module__", None) != modname:
            continue
        if inspect.isclass(obj):
            lines += [f"#### class `{name}{_sig(obj)}`", ""]
            if _doc(obj):
                lines += [_doc(obj), ""]
            for mname, m in sorted(vars(obj).items()):
                if mname.startswith("_") or not inspect.isfunction(m):
                    continue
                lines += [f"- `{mname}{_sig(m)}`" + (f" — {_doc(m).splitlines()[0]}" if _doc(m) else "")]
            lines.append("")
        elif inspect.isfunction(obj):
            lines += [f"#### `{name}{_sig(obj)}`", ""]
            if _doc(obj):
                lines += [_doc(obj), ""]
    return "\n".join(lines)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    pkgs = [m.name for m in pkgutil.iter_modules(nssc.__path__, "nssc.") if m.ispkg and m.name not in SKIP]
    index = ["# API reference (generated by scripts/gen_api_docs.py)", ""]
    for pkg in sorted(pkgs):
        p = importlib.import_module(pkg)
        mods = [pkg] + sorted(m.name for m in pkgutil.walk_packages(p.__path__, pkg + ".")
                              if not m.name.rsplit(".", 1)[-1].startswith("_"))
        body = [f"# `{pkg}`", ""]
        for m in mods:
            try:
                body.append(document_module(m))
            except Exception as e:  # noqa: BLE001
                body.append(f"### `{m}`\n\n(import failed: {e})\n")
        (OUT / f"{pkg.split('.')[-1]}.md").write_text("\n".join(body))
        index.append(f"- [{pkg}]({pkg.split('.')[-1]}.md)")
    for m in ("nssc.experiment",):
        (OUT / "experiment.md").write_text(f"# `{m}`\n\n" + document_module(m))
        index.append(f"- [{m}](experiment.md)")
    (OUT / "README.md").write_text("\n".join(index) + "\n")


if __name__ == "__main__":
    main()
