#!/usr/bin/env python3
"""Regenerate every figure and table from on-disk results (never hand-edited).

    python scripts/generate_report.py [--figures results/figures] [--tables results/tables]

Outputs:
    results/figures/compile/<name>/*.png       per compile run (decision, funnel, pareto, selected model)
    results/figures/suites/<suite>/*.png       per benchmark suite (horizon curves, pareto)
    results/tables/<suite>.md|json             mean ± std tables + paired tests
    results/SUMMARY.md                         index of everything generated, with the compile reports inlined
"""

from __future__ import annotations

import argparse
import glob
from pathlib import Path

from nssc.compiler.report import CompileReport
from nssc.evaluation.tables import suite_tables
from nssc.utils.experiment_registry import ExperimentRegistry
from nssc.visualization.figures import figures_for_compile, figures_for_suite

REFERENCE = {"synthetic_core": "mlpae_resmlp_d3"}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--figures", default="results/figures")
    ap.add_argument("--tables", default="results/tables")
    ap.add_argument("--registry", default="results/registry.jsonl")
    args = ap.parse_args()
    lines = ["# Results index (auto-generated by scripts/generate_report.py)", ""]

    compile_dirs = sorted(p for p in glob.glob("results/compile/**/compile_report.json", recursive=True))
    lines += ["## Compile runs", ""]
    for rp in compile_dirs:
        cdir = Path(rp).parent
        name = str(cdir.relative_to("results/compile"))
        out = Path(args.figures) / "compile" / name
        try:
            paths = figures_for_compile(cdir, out)
            rep = CompileReport.load(rp)
            lines += [f"### {name}", "", f"figures: `{out}` ({len(paths)} files)", "",
                      rep.to_markdown().replace("# Compile report", "#### Compile report"), ""]
        except Exception as e:  # noqa: BLE001
            lines += [f"### {name}", "", f"figure generation failed: {e}", ""]

    suites = sorted({t.split(":", 1)[1] for r in ExperimentRegistry(args.registry).records()
                     for t in r.get("tags", []) if t.startswith("suite:")})
    lines += ["## Benchmark suites", ""]
    for s in suites:
        out = Path(args.figures) / "suites" / s
        try:
            figures_for_suite(args.registry, s, out)
            tab = suite_tables(s, args.registry, args.tables, reference_model=REFERENCE.get(s))
            lines += [f"### {s}", "", f"figures: `{out}`", "", tab["markdown"], ""]
        except Exception as e:  # noqa: BLE001
            lines += [f"### {s}", "", f"failed: {e}", ""]
    Path("results/SUMMARY.md").write_text("\n".join(lines))
    print("wrote results/SUMMARY.md")


if __name__ == "__main__":
    main()
